COMET_STR_MAP={
            'AtLocation': ['located or found at/in/on', 'located or found at', 0, 'physical'],
            'CapableOf': ['is/are capable of', 'is capable of', 0, 'physical'],
            'Causes': ['causes', 'causes', 0, 'event'],
            'CausesDesire': ['makes someone want', 'makes someone want', 0, 'social'],
            'CreatedBy': ['is created by', 'is created by', 0, ''],
            'Desires': ['desires', 'desires', 0, 'physical'],
            'HasA': ['has, possesses or contains', 'has, possesses or contains', 0, 'physical'],
            'HasFirstSubevent': ['BEGINS with the event/action', 'begins with', 0, 'event'],
            'HasLastSubevent': ['ENDS with the event/action', 'ends with', 0, 'event'],
            'HasPrerequisite': ['to do this, one requires', 'requires', 1, 'social'],
            'HasProperty': ['can be characterized by being/having', 'can be characterized by', 0, 'physical'],
            'HasSubEvent': ['includes the event/action', 'includes', 0, 'event'],
            'HinderedBy': ['can be hindered by', 'can be hindered by', 0, 'event'],
            'InstanceOf': ['is an example/instance of', 'is an example of', 0, ''],
            'isAfter': ['happens after', 'happens after', 0, 'event'],
            'isBefore': ['happens before', 'happens before', 0, 'event'],
            'isFilledBy': ['blank can be filled by', 'can be filled by', 0, 'event'],
            'MadeOf': ['is made of', 'is made of', 0, 'physical'],
            'MadeUpOf': ['made (up) of', 'is made up of', 0, 'physical'],
            'MotivatedByGoal': ['is a step towards accomplishing the goal', 'is a step towards accomplishing', 0,
                                'social'],
            'NotDesires': ['do(es) NOT desire', 'does not desire', 0, 'physical'],
            'ObjectUse': ['used for', 'is used for', 0, 'physical'],
            'UsedFor': ['used for', 'is used for', 0, 'physical'],
            'oEffect': ['as a result, Y or others will', 'As a result, PersonY', 1, 'social'],
            'oReact': ['as a result, Y or others feels', 'As a result, PersonY feels', 1, 'social'],
            'oWant': ['as a result, Y or others want', 'As a result, PersonY wants', 1, 'social'],
            'PartOf': ['is a part of', 'is a part of', 0, 'physical'],
            'ReceivesAction': ['can receive or be affected by the action', 'can receive or be affected by', 0, ''],
            'xAttr': ['X is seen as', 'PersonX is seen as', 1, 'social'],
            'xEffect': ['as a result, PersonX will', 'As a result, PersonX', 1, 'social'],
            'xIntent': ['because PersonX wanted', 'because PersonX wanted', 0, 'social'],
            'xNeed': ['but before, PersonX needed', 'but before, PersonX needed', 0, 'social'],
            'xReact': ['as a result, PersonX feels', 'As a result, PersonX feels', 1, 'social'],
            'xReason': ['because', 'because', 0, 'event'],
            'xWant': ['as a result, PersonX wants', 'As a result, PersonX wants', 1, 'social']
        }

EMOTION2LABEL = {
    'surprised': 0, 'excited': 1, 'annoyed': 2, 'proud': 3, 'angry': 4, 'sad': 5, 'grateful': 6, 'lonely': 7,
    'impressed': 8, 'afraid': 9, 'disgusted': 10, 'confident': 11, 'terrified': 12, 'hopeful': 13,
    'anxious': 14, 'disappointed': 15,
    'joyful': 16, 'prepared': 17, 'guilty': 18, 'furious': 19, 'nostalgic': 20, 'jealous': 21,
    'anticipating': 22, 'embarrassed': 23,
    'content': 24, 'devastated': 25, 'sentimental': 26, 'caring': 27, 'trusting': 28, 'ashamed': 29,
    'apprehensive': 30, 'faithful': 31}
LABLE2EMOTION = {0: 'surprised', 1: 'excited', 2: 'annoyed', 3: 'proud',
                4: 'angry', 5: 'sad', 6: 'grateful', 7: 'lonely', 8: 'impressed',
                9: 'afraid', 10: 'disgusted', 11: 'confident', 12: 'terrified',
                13: 'hopeful', 14: 'anxious', 15: 'disappointed', 16: 'joyful',
                17: 'prepared', 18: 'guilty', 19: 'furious', 20: 'nostalgic',
                21: 'jealous', 22: 'anticipating', 23: 'embarrassed', 24: 'content',
                25: 'devastated', 26: 'sentimental', 27: 'caring', 28: 'trusting',
                29: 'ashamed', 30: 'apprehensive', 31: 'faithful'}

entity_relation = ['ObjectUse', 'AtLocation', 'MadeUpOf', 'HasProperty']
entity_relation_map = {"ObjectUse": "used for", "AtLocation": "located at", "MadeUpOf": "made up of",
                            "HasProperty": "has property"}